/*
 * UB E-Health - AI Report Interpreter Service
 * Copyright (c) 2025-2026 Shaishav
 * Licensed under MIT License
 */

/**
 * AI Report Interpreter Service
 * Converts complex medical terminology into patient-friendly language
 */

/**
 * Interprets lab report results and generates patient-friendly summary
 * @param {Object} labReport - The lab report object with results
 * @returns {Object} Structured interpretation with sections
 */
function interpretLabReport(labReport) {
  const { results, testType, testName, status } = labReport;
  
  if (!results || !results.parameters || results.parameters.length === 0) {
    return {
      error: "No results available to interpret",
      message: "This report does not contain test results yet."
    };
  }

  // Analyze parameters
  const normalCount = results.parameters.filter(p => p.status === "Normal").length;
  const highCount = results.parameters.filter(p => p.status === "High").length;
  const lowCount = results.parameters.filter(p => p.status === "Low").length;
  const criticalCount = results.parameters.filter(p => p.status === "Critical").length;
  const totalCount = results.parameters.length;

  // Generate executive summary
  const executiveSummary = generateExecutiveSummary(
    testName,
    normalCount,
    highCount,
    lowCount,
    criticalCount,
    totalCount
  );

  // Explain each parameter
  const parametersExplained = results.parameters.map(param => 
    explainParameter(param, testType)
  );

  // Generate recommendations
  const recommendations = generateRecommendations(
    results.parameters,
    testType,
    highCount,
    lowCount,
    criticalCount
  );

  // Generate questions for doctor
  const questionsForDoctor = generateDoctorQuestions(
    results.parameters,
    testType
  );

  return {
    executiveSummary,
    parametersExplained,
    recommendations,
    questionsForDoctor,
    technicalSummary: results.summary,
    technicalRemarks: results.remarks,
    disclaimer: "This summary is generated by AI for educational purposes only. Please consult your physician before making any medical decisions."
  };
}

/**
 * Generates executive summary based on overall results
 */
function generateExecutiveSummary(testName, normal, high, low, critical, total) {
  let summary = `Your ${testName} test has been completed. `;
  
  if (critical > 0) {
    summary += `⚠️ IMPORTANT: ${critical} parameter(s) show critical values that require immediate medical attention. `;
  } else if (high > 0 || low > 0) {
    summary += `${high + low} parameter(s) are outside the normal range and may need attention. `;
  } else {
    summary += `All ${total} parameters are within normal ranges. `;
  }
  
  summary += "Please review the detailed explanation below and discuss with your doctor.";
  
  return summary;
}

/**
 * Explains individual parameter in layman's terms
 */
function explainParameter(param, testType) {
  const { name, value, unit, normalRange, status } = param;
  
  // Get layman explanation for common parameters
  const explanation = getParameterExplanation(name, testType);
  
  // Status interpretation
  let statusText = "";
  let icon = "";
  
  switch (status) {
    case "Normal":
      statusText = "This is within the healthy range.";
      icon = "✓";
      break;
    case "High":
      statusText = "This is higher than the normal range.";
      icon = "↑";
      break;
    case "Low":
      statusText = "This is lower than the normal range.";
      icon = "↓";
      break;
    case "Critical":
      statusText = "⚠️ This requires immediate medical attention.";
      icon = "⚠️";
      break;
  }
  
  return {
    parameter: name,
    value: `${value} ${unit}`,
    normalRange: normalRange,
    status: status,
    icon: icon,
    whatItMeans: explanation,
    interpretation: statusText
  };
}

/**
 * Returns layman explanation for common lab parameters
 */
function getParameterExplanation(paramName, testType) {
  const explanations = {
    // Complete Blood Count (CBC)
    "Hemoglobin": "Hemoglobin is the protein in red blood cells that carries oxygen throughout your body. Low levels may indicate anemia (feeling tired/weak), while high levels could suggest dehydration or other conditions.",
    "Hematocrit": "This measures the percentage of red blood cells in your blood. It helps assess if you have enough red blood cells to carry oxygen.",
    "WBC Count": "White Blood Cells (WBC) are your body's defense system against infections. High counts may indicate infection or inflammation, while low counts could mean weakened immunity.",
    "RBC Count": "Red Blood Cells (RBC) carry oxygen from your lungs to the rest of your body. Abnormal levels can affect your energy and overall health.",
    "Platelet Count": "Platelets help your blood clot to stop bleeding. Low counts increase bleeding risk, while high counts may increase clotting risk.",
    "MCV": "Mean Corpuscular Volume measures the average size of your red blood cells. It helps identify the type of anemia if present.",
    "MCH": "Mean Corpuscular Hemoglobin measures the average amount of hemoglobin in each red blood cell.",
    "MCHC": "This measures the concentration of hemoglobin in red blood cells.",
    
    // Lipid Profile
    "Total Cholesterol": "Cholesterol is a fatty substance in your blood. High levels can increase your risk of heart disease and stroke.",
    "LDL Cholesterol": "Often called 'bad cholesterol,' high LDL can build up in arteries and increase heart disease risk.",
    "HDL Cholesterol": "Known as 'good cholesterol,' HDL helps remove bad cholesterol from your arteries. Higher is better.",
    "Triglycerides": "These are fats in your blood. High levels increase risk of heart disease and can be affected by diet and lifestyle.",
    "VLDL": "Very Low-Density Lipoprotein carries triglycerides. High levels contribute to plaque buildup in arteries.",
    
    // Blood Sugar
    "Blood Glucose": "This measures sugar (glucose) in your blood. High levels may indicate diabetes or prediabetes.",
    "Fasting Blood Sugar": "This test measures blood sugar after not eating for 8-12 hours. It's used to screen for diabetes.",
    "Random Blood Sugar": "This measures blood sugar at any time of day, regardless of when you last ate.",
    "HbA1c": "This shows your average blood sugar levels over the past 2-3 months. It's a key test for diabetes management.",
    
    // Liver Function
    "ALT": "Alanine Aminotransferase is an enzyme in the liver. High levels may indicate liver damage or inflammation.",
    "AST": "Aspartate Aminotransferase is another liver enzyme. Elevated levels can signal liver or heart problems.",
    "Bilirubin": "This is produced when red blood cells break down. High levels can cause jaundice (yellowing of skin/eyes).",
    "Alkaline Phosphatase": "This enzyme is found in liver and bones. High levels may indicate liver or bone disorders.",
    "Total Protein": "This measures all proteins in your blood, important for many body functions.",
    "Albumin": "The main protein in blood, made by the liver. Low levels may indicate liver or kidney problems.",
    
    // Kidney Function
    "Creatinine": "A waste product filtered by kidneys. High levels may indicate kidney problems.",
    "BUN": "Blood Urea Nitrogen measures waste in blood. High levels may suggest kidney issues or dehydration.",
    "eGFR": "Estimated Glomerular Filtration Rate shows how well your kidneys are filtering waste.",
    "Uric Acid": "High levels can cause gout (painful joint inflammation) or kidney stones.",
    
    // Thyroid
    "TSH": "Thyroid Stimulating Hormone controls your thyroid gland. Abnormal levels indicate thyroid problems affecting metabolism.",
    "T3": "Triiodothyronine is a thyroid hormone that regulates metabolism, heart rate, and body temperature.",
    "T4": "Thyroxine is the main thyroid hormone. It affects almost every organ in your body.",
    
    // Vitamins
    "Vitamin D": "Essential for bone health, immune function, and mood. Low levels are common and can cause fatigue and bone pain.",
    "Vitamin B12": "Important for nerve function and red blood cell production. Low levels can cause anemia and nerve problems.",
    "Folate": "Also called Vitamin B9, essential for cell growth and DNA production.",
    
    // Electrolytes
    "Sodium": "An electrolyte that helps regulate fluid balance and nerve/muscle function.",
    "Potassium": "Critical for heart rhythm and muscle function. Abnormal levels can be dangerous.",
    "Calcium": "Essential for bones, teeth, and muscle function. Also important for heart rhythm.",
    "Magnesium": "Important for muscle and nerve function, blood sugar control, and blood pressure."
  };
  
  return explanations[paramName] || `${paramName} is a parameter measured in your ${testType} test. Please discuss the significance with your doctor.`;
}

/**
 * Generates lifestyle recommendations based on results
 */
function generateRecommendations(parameters, testType, highCount, lowCount, criticalCount) {
  const recommendations = [];
  
  // Critical values - immediate action
  if (criticalCount > 0) {
    recommendations.push({
      priority: "URGENT",
      icon: "⚠️",
      title: "Seek Immediate Medical Attention",
      description: "Your results show critical values that require prompt evaluation by a healthcare provider. Please contact your doctor immediately or visit an emergency facility."
    });
  }
  
  // Analyze specific parameters for targeted advice
  parameters.forEach(param => {
    if (param.status === "High" || param.status === "Low") {
      const advice = getParameterAdvice(param.name, param.status);
      if (advice && !recommendations.find(r => r.title === advice.title)) {
        recommendations.push(advice);
      }
    }
  });
  
  // General recommendations
  if (highCount > 0 || lowCount > 0) {
    recommendations.push({
      priority: "Important",
      icon: "📋",
      title: "Schedule a Follow-up Appointment",
      description: "Discuss these results with your doctor to understand what they mean for your health and what steps to take next."
    });
  }
  
  // Always include general wellness advice
  recommendations.push({
    priority: "General",
    icon: "💪",
    title: "Maintain Healthy Lifestyle Habits",
    description: "Continue or adopt healthy habits: balanced diet, regular exercise, adequate sleep (7-9 hours), stress management, and staying hydrated."
  });
  
  return recommendations;
}

/**
 * Gets specific advice for abnormal parameters
 */
function getParameterAdvice(paramName, status) {
  const advice = {
    "Hemoglobin": {
      Low: {
        priority: "Important",
        icon: "🥗",
        title: "Increase Iron-Rich Foods",
        description: "Consider eating more iron-rich foods like lean red meat, spinach, beans, and fortified cereals. Vitamin C helps iron absorption."
      },
      High: {
        priority: "Important",
        icon: "💧",
        title: "Stay Well Hydrated",
        description: "Ensure adequate fluid intake. High hemoglobin can sometimes indicate dehydration."
      }
    },
    "Blood Glucose": {
      High: {
        priority: "Important",
        icon: "🍎",
        title: "Monitor Blood Sugar and Diet",
        description: "Limit sugary foods and refined carbohydrates. Focus on whole grains, vegetables, lean proteins, and regular physical activity."
      },
      Low: {
        priority: "Important",
        icon: "🍬",
        title: "Prevent Low Blood Sugar",
        description: "Eat regular meals and snacks. Keep quick-acting carbohydrates available if you experience symptoms of low blood sugar."
      }
    },
    "Total Cholesterol": {
      High: {
        priority: "Important",
        icon: "❤️",
        title: "Heart-Healthy Diet",
        description: "Reduce saturated fats, increase fiber intake, eat more fish, nuts, and olive oil. Regular exercise can help lower cholesterol."
      }
    },
    "LDL Cholesterol": {
      High: {
        priority: "Important",
        icon: "🥑",
        title: "Lower Bad Cholesterol",
        description: "Limit red meat, full-fat dairy, and fried foods. Choose lean proteins, whole grains, and plenty of fruits and vegetables."
      }
    },
    "Triglycerides": {
      High: {
        priority: "Important",
        icon: "🚫",
        title: "Reduce Triglycerides",
        description: "Limit alcohol, sugar, and refined carbs. Increase omega-3 fatty acids from fish. Regular exercise is very effective."
      }
    },
    "Vitamin D": {
      Low: {
        priority: "Important",
        icon: "☀️",
        title: "Increase Vitamin D",
        description: "Get safe sun exposure (10-15 minutes daily), eat vitamin D-rich foods (fatty fish, egg yolks, fortified milk), or consider supplements as advised by your doctor."
      }
    }
  };
  
  return advice[paramName]?.[status] || null;
}

/**
 * Generates relevant questions patient should ask their doctor
 */
function generateDoctorQuestions(parameters, testType) {
  const questions = [];
  
  // Check for abnormal values
  const abnormalParams = parameters.filter(p => p.status !== "Normal");
  
  if (abnormalParams.length > 0) {
    questions.push(`What do my abnormal ${testType} results mean for my overall health?`);
    questions.push(`Do I need any additional tests or follow-up appointments?`);
    questions.push(`Are there specific lifestyle changes or treatments you recommend based on these results?`);
  } else {
    questions.push(`How often should I repeat this ${testType} test?`);
    questions.push(`Are there any preventive measures I should take to maintain these healthy levels?`);
    questions.push(`Should I be monitoring any specific symptoms at home?`);
  }
  
  // Add parameter-specific questions
  abnormalParams.slice(0, 2).forEach(param => {
    const specificQuestion = getParameterQuestion(param.name, param.status);
    if (specificQuestion) {
      questions.push(specificQuestion);
    }
  });
  
  return questions.slice(0, 5); // Limit to 5 questions
}

/**
 * Gets specific question for abnormal parameter
 */
function getParameterQuestion(paramName, status) {
  const questions = {
    "Hemoglobin": "Could my hemoglobin level be related to my diet, or should we investigate other causes?",
    "Blood Glucose": "What is my risk for diabetes, and what steps should I take to manage my blood sugar?",
    "Total Cholesterol": "What is my cardiovascular risk, and do I need medication or can lifestyle changes help?",
    "Creatinine": "How is my kidney function, and are there any dietary restrictions I should follow?",
    "TSH": "Do I have a thyroid condition, and what treatment options are available?",
    "Vitamin D": "Should I take vitamin D supplements, and what dosage would you recommend?"
  };
  
  return questions[paramName] || null;
}

module.exports = {
  interpretLabReport
};
