// Lab Personnel Action Types

// Add Lab Personnel
export const ADD_LAB_PERSONNEL_REQUEST = "ADD_LAB_PERSONNEL_REQUEST";
export const ADD_LAB_PERSONNEL_SUCCESS = "ADD_LAB_PERSONNEL_SUCCESS";
export const ADD_LAB_PERSONNEL_ERROR = "ADD_LAB_PERSONNEL_ERROR";

// Get All Lab Personnel
export const GET_ALL_LAB_PERSONNEL_REQUEST = "GET_ALL_LAB_PERSONNEL_REQUEST";
export const GET_ALL_LAB_PERSONNEL_SUCCESS = "GET_ALL_LAB_PERSONNEL_SUCCESS";
export const GET_ALL_LAB_PERSONNEL_ERROR = "GET_ALL_LAB_PERSONNEL_ERROR";

// Get Lab Personnel By ID
export const GET_LAB_PERSONNEL_BY_ID_REQUEST = "GET_LAB_PERSONNEL_BY_ID_REQUEST";
export const GET_LAB_PERSONNEL_BY_ID_SUCCESS = "GET_LAB_PERSONNEL_BY_ID_SUCCESS";
export const GET_LAB_PERSONNEL_BY_ID_ERROR = "GET_LAB_PERSONNEL_BY_ID_ERROR";

// Update Lab Personnel
export const UPDATE_LAB_PERSONNEL_REQUEST = "UPDATE_LAB_PERSONNEL_REQUEST";
export const UPDATE_LAB_PERSONNEL_SUCCESS = "UPDATE_LAB_PERSONNEL_SUCCESS";
export const UPDATE_LAB_PERSONNEL_ERROR = "UPDATE_LAB_PERSONNEL_ERROR";

// Delete Lab Personnel
export const DELETE_LAB_PERSONNEL_REQUEST = "DELETE_LAB_PERSONNEL_REQUEST";
export const DELETE_LAB_PERSONNEL_SUCCESS = "DELETE_LAB_PERSONNEL_SUCCESS";
export const DELETE_LAB_PERSONNEL_ERROR = "DELETE_LAB_PERSONNEL_ERROR";

// Lab Personnel Login
export const LAB_PERSONNEL_LOGIN_REQUEST = "LAB_PERSONNEL_LOGIN_REQUEST";
export const LAB_PERSONNEL_LOGIN_SUCCESS = "LAB_PERSONNEL_LOGIN_SUCCESS";
export const LAB_PERSONNEL_LOGIN_ERROR = "LAB_PERSONNEL_LOGIN_ERROR";
