// Lab Reports Action Types

// Get All Lab Reports
export const GET_ALL_LAB_REPORTS_REQUEST = "GET_ALL_LAB_REPORTS_REQUEST";
export const GET_ALL_LAB_REPORTS_SUCCESS = "GET_ALL_LAB_REPORTS_SUCCESS";
export const GET_ALL_LAB_REPORTS_ERROR = "GET_ALL_LAB_REPORTS_ERROR";

// Update Lab Report Status
export const UPDATE_LAB_REPORT_STATUS_REQUEST = "UPDATE_LAB_REPORT_STATUS_REQUEST";
export const UPDATE_LAB_REPORT_STATUS_SUCCESS = "UPDATE_LAB_REPORT_STATUS_SUCCESS";
export const UPDATE_LAB_REPORT_STATUS_ERROR = "UPDATE_LAB_REPORT_STATUS_ERROR";

// Add Lab Report Results
export const ADD_LAB_REPORT_RESULTS_REQUEST = "ADD_LAB_REPORT_RESULTS_REQUEST";
export const ADD_LAB_REPORT_RESULTS_SUCCESS = "ADD_LAB_REPORT_RESULTS_SUCCESS";
export const ADD_LAB_REPORT_RESULTS_ERROR = "ADD_LAB_REPORT_RESULTS_ERROR";

// Get Home Service Requests
export const GET_HOME_SERVICE_REQUESTS_REQUEST = "GET_HOME_SERVICE_REQUESTS_REQUEST";
export const GET_HOME_SERVICE_REQUESTS_SUCCESS = "GET_HOME_SERVICE_REQUESTS_SUCCESS";
export const GET_HOME_SERVICE_REQUESTS_ERROR = "GET_HOME_SERVICE_REQUESTS_ERROR";

// Get Patient Lab History
export const GET_PATIENT_LAB_HISTORY_REQUEST = "GET_PATIENT_LAB_HISTORY_REQUEST";
export const GET_PATIENT_LAB_HISTORY_SUCCESS = "GET_PATIENT_LAB_HISTORY_SUCCESS";
export const GET_PATIENT_LAB_HISTORY_ERROR = "GET_PATIENT_LAB_HISTORY_ERROR";
