// Payment Action Types

// Create payment order
export const CREATE_PAYMENT_ORDER_REQUEST = "CREATE_PAYMENT_ORDER_REQUEST";
export const CREATE_PAYMENT_ORDER_SUCCESS = "CREATE_PAYMENT_ORDER_SUCCESS";
export const CREATE_PAYMENT_ORDER_FAILURE = "CREATE_PAYMENT_ORDER_FAILURE";

// Verify payment
export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAILURE = "VERIFY_PAYMENT_FAILURE";

// Get payment history
export const GET_PAYMENT_HISTORY_REQUEST = "GET_PAYMENT_HISTORY_REQUEST";
export const GET_PAYMENT_HISTORY_SUCCESS = "GET_PAYMENT_HISTORY_SUCCESS";
export const GET_PAYMENT_HISTORY_FAILURE = "GET_PAYMENT_HISTORY_FAILURE";

// Get payment details
export const GET_PAYMENT_DETAILS_REQUEST = "GET_PAYMENT_DETAILS_REQUEST";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
export const GET_PAYMENT_DETAILS_FAILURE = "GET_PAYMENT_DETAILS_FAILURE";

// Request refund
export const REQUEST_REFUND_REQUEST = "REQUEST_REFUND_REQUEST";
export const REQUEST_REFUND_SUCCESS = "REQUEST_REFUND_SUCCESS";
export const REQUEST_REFUND_FAILURE = "REQUEST_REFUND_FAILURE";

// Get payment methods
export const GET_PAYMENT_METHODS_REQUEST = "GET_PAYMENT_METHODS_REQUEST";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const GET_PAYMENT_METHODS_FAILURE = "GET_PAYMENT_METHODS_FAILURE";

// Clear payment state
export const CLEAR_PAYMENT_STATE = "CLEAR_PAYMENT_STATE";
